import { CSSObjectWithLabel } from "react-select";

import { TabInfoType } from "@/_types/common/Info";

export const BASE_API_ENDPOINT = `${process.env.NEXT_PUBLIC_API_URL}`;
export const FILE_TYPE = {
  IMAGE: {
    "image/png": [".png"],
    "image/jpeg": [".jpeg"],
    "image/jpg": [".jpg"],
  },
  VIDEO: {
    "video/mp4": [".mp4"],
    "video/mpeg": [".mpeg"],
    "video/quicktime": [".mov"],
    "video/webm": [".webm"],
  },
  PDF: {
    "application/pdf": [".pdf"],
  },
  CSV: {
    "text/csv": [".csv"],
  },
  XLSX: {
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [
      ".xlsx",
    ],
  },
};

export const FILE_SIZE_TYPE = {
  MB: 1024,
};

export const CONFIG = {
  STATUS_CODES: {
    UNAUTHORIZED: 401,
    NO_CONTENT: 204,
    NOT_FOUND: 404,
  },
  AUTH_TOKEN_EXP: "auth_token_exp",
  PARAMS: {
    REDIRECT_URL_PARAM: "next",
  },
  PAGE_SIZE_OPTIONS: { 12: 12, 24: 24, 48: 48, 96: 96 },
  PAGINATION: {
    PAGE: 1,
    SIZE: 12,
    TYPE: "page",
  },
  MESSAGES: {
    GENERIC_ERROR: "Something went wrong",
    SUCCESS: "Details updated successfully",
    NO_RECORDS_FOUND: "No records found in the uploaded file",
    USER_ADDED_SUCCESSFULLY: "User Added Successfully",
    MEDIA_DETAILS_ADDED_SUCCESSFULLY: "Media details added successfully",
    DATA_DELETE: "Data deleted successfully",
    DISTRIBUTOR_ADDED_SUCCESSFULLY: "Distributor added successfully",
    DISTRIBUTOR_UPDATED_SUCCESSFULLY: "Distributor updated successfully",
    PASSWORD_ADDED_SUCCESSFULLY: "Password updated successfully",
    ALBUM_ADDED_SUCCESSFULLY: "Album added successfully",
    SEASON_ADDED_SUCCESSFULLY: "Season added successfully",
    EPISODE_ADDED_SUCCESSFULLY: "Episode added successfully",
    SONG_ADDED_SUCCESSFULLY: "Song added successfully",
    SYSTEM_ADDED_SUCCESSFULLY: "System added successfully",
    TRANSLATION_ADDED_SUCCESSFULLY: "Translation added successfully",
    TRANSLATION_UPDATED_SUCCESSFULLY: "Translation updated successfully",
    TRAILER_ADDED_SUCCESSFULLY: "Trailer added successfully",
    TRAILER_EDITED_SUCCESSFULLY: "Trailer edited successfully",
    CONFIRM_DELETE_IMAGE: "Are you sure you want to delete this Image?",
    FILE_UPLOAD_WARNING:
      "Are you sure you want to continue without uploading attached file? ",
    YOU_HAVE_SUCCESSFULLY_LOGGED_IN: "You have successfully logged in!",
    ONLY_XLSX_ACCEPTED: "only .xlsx file are accepted",
    METADATA_ADDED_SUCCESSFULLY: "Metadata added successfully",
    DETAILS_ADDED_SUCCESSFULLY: "Details added successfully",
  },
  CODE: {
    INVALID_FILE_TYPE: "file-invalid-type",
  },
  VALIDATION: {
    MESSAGE: {
      MAX_NAME_LIMIT_255:
        "This field must be less than or equal to 255 characters",
      NUMERICAL_VALUES_REQUIRED: "Only numerical values are allowed",
      NUMERICAL_VALUE_RANGE_FROM_ONE_TO_MAX_INT_LIMIT:
        "Duration must be in range of 1 and 35791394",
      METACRITIC_FORMAT_DESCRIPTION:
        "Metacritic cannot be greater than 100 and can have max 2 digit after the decimal point.",
      IMDB_FORMAT_DESCRIPTION:
        "IMDB rating cannot be greater than 10 and can have max 2 digit after the decimal point.",
      ROTTEN_TOMATOES_AUDIENCE:
        "Rotten tomatoes audience rating cannot be greater than 100 and can have max 2 digit after the decimal point.",
      ROTTEN_TOMATOES_CRITICS:
        "Rotten tomatoes critic rating cannot be greater than 100 and can have max 2 digit after the decimal point.",
      USER_FIRST_NAME:
        "First Name can only contain alphabets single quotes, and spaces",
      USER_LAST_NAME:
        "Last Name can only contain alphabets single quotes, and spaces",
      USER_EMAIL_REQUIRED: "Email address is required",
      USER_PASSWORD:
        "Must contain a combination of letters, numbers and special character with one uppercase and lowercase character",
      PASSWORD_DO_NOT_MATCH: "Password do not match",
      INVALID_URL: "Invalid URL",
    },
    CHARACTER_LENGTH: {
      TWO_HUNDREAD_CHARACTERS: 200,
      TWO_FIFTY_FIVE_CHARACTERS: 255,
      THREE_HUNDREAD_CHARACTERS: 300,
      EIGHT_CHARACTERS: 8,
      FIVE_HUNDREAD_CHARACTERS: 500,
      ONE_HUNDREAD_CHARACTERS: 100,
    },
    FIELD_NAME: {
      USER_FIRST_NAME: "First name",
      USER_LAST_NAME: "Last name",
      ISRC: "ISRC",
      ROLE: "Role",
      LOG_NO: "Log no.",
      PRODUCTION_NO: "Production no.",
      SONG_TITLE: "Song Title",
      SYNOPSIS: "Synopsis",
      ORIGINAL_TITLE: "Original title",
      THIS_FIELD: "This field",
      JOB_TITLE: "Job title",
      TITLE: "Title",
      ARTIST_NAME: "Artist name",
      ALBUM_TITLE: "Album title",
      PODCAST_NAME: "Podcast name",
      PASSWORD: "Password",
      EMAIL: "Email",
      NAME: "Name",
      BIT_RATE: "Bit rate",
      LANGUAGE: "Language",
      TYPE: "Type",
      CATEGORY: "category",
      ASSET: "asset",
      URL: "URL",
      SCREENER_LINK: "Screener link",
    },
  },
  TOASTER_OPTIONS: {
    SUCCESS: {
      duration: 6000,
      style: {
        maxWidth: 450,
        borderRadius: "10px",
      },
    },
    ERROR: {
      duration: 6000,
      style: {
        maxWidth: 450,
        borderRadius: "10px",
      },
    },
    HOLD: {
      duration: 6000,
      style: {
        maxWidth: 450,
        borderRadius: "10px",
        background: "#FFFF00",
        color: "#000",
      },
    },
  },
  COLOR_ARRAY: {
    colorArray: [
      "#FF6633",
      "#FFB399",
      "#00B3E6",
      "#E6B333",
      "#3366E6",
      "#999966",
      "#99FF99",
      "#B34D4D",
      "#80B300",
      "#809900",
      "#E6B3B3",
      "#6680B3",
      "#66991A",
      "#FF99E6",
      "#CCFF1A",
      "#FF1A66",
      "#E6331A",
      "#33FFCC",
      "#66994D",
      "#B366CC",
      "#4D8000",
      "#B33300",
      "#CC80CC",
      "#66664D",
      "#991AFF",
      "#E666FF",
      "#4DB3FF",
      "#1AB399",
      "#E666B3",
      "#33991A",
      "#CC9999",
      "#B3B31A",
      "#00E680",
      "#4D8066",
      "#809980",
      "#E6FF80",
      "#1AFF33",
      "#999933",
      "#FF3380",
      "#CCCC00",
      "#66E64D",
      "#4D80CC",
      "#9900B3",
      "#E64D66",
      "#4DB380",
      "#FF4D4D",
      "#99E6E6",
      "#6666FF",
    ],
  },
  DEBOUNCE_TIMEOUT: 500,
  WORD_SLICE_LIMIT: 50,
  WATCH_TRAILER_WORD_LIMIT: 80,
  USER_CARD_WORD_SLICE_LIMIT: 20,
  WORD_SLICE_LIMIT_TWENTY_FIVE: 25,
  DROPDOWN_LABEL_SLICE_LIMIT: 30,
  WORD_SLICE_LIMIT_FOURTY: 40,
  PLUGINS_JS_PATH: "../js/scripts.bundle.js",
  SWEETALERT_DELETE_OPTION: {
    text: "Are you sure you want to delete",
    icon: "warning",
    showCancelButton: true,
    confirmButtonColor: "#d33",
    cancelButtonColor: "#3085d6",
    confirmButtonText: "Yes",
    cancelButtonText: "Cancel",
  },
  SWEETALERT_DUB_MESSAGE: "this dub",
  SWEETALERT_SUB_MESSAGE: "this sub",
  FIELD_IGNORE: {
    ARTIST: "__ARTIST__",
    ALBUM: "__ALBUM__",
  },
  SWEETALERT_SUCCESS_OPTION: {
    icon: "success",
    showConfirmButton: false,
    timer: 5000,
  },
  IMAGE_SIZE: {
    CARD: "160x160",
    TABLE_LIST: "50x50",
    USER_CARD: "65x65",
    MEDIA_IMAGES: "300x300",
    MEDIA_LIBRARY_IMAGES: "60x80",
    MEDIA_LIBRAY_CARD_IMAGES: "307x454",
    LOGGED_IN_USER_HEADER_IMAGE: "40x40",
    MEDIA_LIBRARY_INFO_HEADER: "108x160",
  },
  SWEETALERT_ERROR_OPTION: {
    icon: "error",
  },
  SWEETALERT_WARNING_OPTION: {
    icon: "warning",
  },
  USER_MENU_TIMEOUT: 250,
  SKELETON_CONFIGURATION: {
    SKELETON_ROWS_COUNT: 5,
    SKELETON_HEIGHT: 60,
  },
  REDIRECT_TIMEOUT: 500,
  INFO_TABS: {
    FILE_INFO: {
      label: "File Info",
      path: "info",
    },
    LANGUAGES: {
      label: "Languages",
      path: "languages",
    },
    METADATA: {
      label: "Metadata",
      path: "metadata",
    },
    TRAILER: {
      label: "Trailer",
      path: "trailer",
    },
    IMAGES: {
      label: "Images",
      path: "images",
    },
    // SCHEDULE: {
    //     label: "Schedule",
    //     path: "schedule",
    // },
    // ANALYTICS: {
    //     label: "Analytics",
    //     path: "analytics",
    // },
    SEASONS: {
      label: "Seasons",
      path: "seasons",
    },
    EPISODES: {
      label: "Episodes",
      path: "episode",
    },
    ALBUMS: {
      label: "Albums",
      path: "albums",
    },
    SONGS: {
      label: "Songs",
      path: "songs",
    },
  },
  FILE_INFO_FORM_FIELD_NAME: {
    NAME: "name",
    DURATION: "duration",
    RIGHTS: "rights",
    DIRECTOR: "director",
    MPAA: "mpaa",
    CAST: "cast",
    SYNOPSIS: "synopsis",
    GENRES: "genres",
    THEATRICAL: "theatrical",
    IFE: "ife",
    DISTRIBUTOR: "distributor",
    LAB: "lab",
    VERSION: "version",
    ORIGIN_COUNTRY_CODE: "origin_country_code",
    LOG_NO: "log_no",
    AVAILABILITY: "availability",
    CATEGORY: "category",
    WIRELESS: "wireless",
    DRM: "drm",
    IMDB: "imdb",
    METACRITIC_CRITICS: "metacritic_critics",
    ROTTEN_TOMATOES_AUDIENCE: "rotten_tomatoes_audience",
    ROTTEN_TOMATOES_CRITICS: "rotten_tomatoes_critics",
    DATE: "date",
    CREATOR: "creator",
    PRODUCTION_NO: "production_no",
    FEATURED_ARTISTS: "featured_artist",
    EXPLICIT: "explicit",
    ISRC: "isrc",
    PRODUCERS: "producer",
    HOSTS: "host",
    NARRATOR: "narrator",
    WRITER: "writer",
    COVER: "cover",
    FORM_HEADING: "form_heading",
  },
  API_ENDPOINTS: {
    FILES: new URL(`${BASE_API_ENDPOINT}/files`),
    TRAILER: new URL(`${BASE_API_ENDPOINT}/trailers`),
    DISTRIBUTOR: new URL(`${BASE_API_ENDPOINT}/distributors`),
    MEDIA: new URL(`${BASE_API_ENDPOINT}/assets`),
    LAB: new URL(`${BASE_API_ENDPOINT}/labs`),
    CATEGORY: new URL(`${BASE_API_ENDPOINT}/categories`),
    GENRE: new URL(`${BASE_API_ENDPOINT}/genres`),
    ADMIN: new URL(`${BASE_API_ENDPOINT}/admins`),
    SYSTEM: new URL(`${BASE_API_ENDPOINT}/systems`),
    LANGUAGE: new URL(`${BASE_API_ENDPOINT}/languages`),
    TRANSLATION: new URL(`${BASE_API_ENDPOINT}/translations`),
    TRANSLATION_CATEGORY: new URL(
      `${BASE_API_ENDPOINT}/translation-categories`
    ),
    LOGOUT: new URL(`${BASE_API_ENDPOINT}/user/logout`),
    CONTACTS: new URL(`${BASE_API_ENDPOINT}/contacts`),
    REQUEST_RESET_PASSWORD: new URL(
      `${BASE_API_ENDPOINT}/user/request-reset-password`
    ),
    RESET_PASSWORD: new URL(`${BASE_API_ENDPOINT}/user/reset-password`),
    LOGIN: new URL(`${BASE_API_ENDPOINT}/user/login`),
    IMAGES: new URL(`${BASE_API_ENDPOINT}/images`),
    USER_INFO: new URL(`${BASE_API_ENDPOINT}/user/info`),
    ROLE: new URL(`${BASE_API_ENDPOINT}/roles`),
    ASSET_IMAGES: new URL(`${BASE_API_ENDPOINT}/asset-images`),
    SYNPOSES: new URL(`${BASE_API_ENDPOINT}/synopses`),
    BULK_UPLOADS: new URL(`${BASE_API_ENDPOINT}/bulk-uploads`),
    REFRESH_TOKEN: new URL(
      `${process.env.NEXT_PUBLIC_API_URL}/user/refresh-token`
    ),
  },
  DUB_OR_SUB_FORM_FIELD: {
    LANGUAGE: "language",
    STATUS: "status",
    ASPECT_RATIO: "aspect_ratio",
    BIT_RATE: "bit_rate",
    ENCODING: "encoding",
    SYSTEMS: "systems",
    SUB_TYPE: "sub_type",
  },
  MEDIA_LIBRARY_TABS: {
    movies: {
      label: "Movies",
      path: "movies",
    },
    "tv-shows": {
      label: "TV Shows",
      path: "tv-shows",
    },
    audio: {
      label: "Audio",
      path: "audio",
    },
    publications: {
      label: "Publications",
      path: "publications",
    },
    games: {
      label: "Games",
      path: "games",
    },
  } as Record<string, TabInfoType>,
  SIGN_IN_TITLE: "Sign in to IFD Hub",
  MAX_INT_LIMIT: 35791394,
  DROPDOWN_STYLE: {
    menu: (base: CSSObjectWithLabel) => ({ ...base, zIndex: "9" }),
    valueContainer: (base: CSSObjectWithLabel) => ({
      ...base,
      maxHeight: "37px",
      overflow: "auto",
    }),
    singleValue: (base: CSSObjectWithLabel) => ({
      ...base,
      color: "#5e6278",
      fontWeight: 500,
      fontSize: "14px",
    }),
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    option: (base: CSSObjectWithLabel, state: any) => ({
      ...base,
      color:
        state.isDisabled && state.isSelected
          ? "#fff"
          : state.isDisabled
          ? "#808080"
          : state.isSelected
          ? "#fff"
          : "#242565",
      ":hover": { backgroundColor: state.isSelected ? "#242565" : "#DEEBFF" },
      backgroundColor: state.isSelected ? "#242565" : "none",
    }),
  },
  REACT_TABLE: {
    FIX_TABLE_DATA_COLUMN_SIZE: 100,
    TABLE_BUTTON_COLUMN_SIZE: 250,
    PODCAST_COLUMN_SIZE: 240,
    RUNTIME_SIZE: 200,
  },
  LOCAL_STORAGE_VARIABLES: {
    ACCESS_TOKEN: "X-Auth-Access-Token",
    REFRESH_TOKEN: "X-Auth-Refresh-Token",
  },
  TOKEN_EXPIRY_TIME: 120000,
  REFRESH_TOKEN_MEMOIZED_TIME: 10000,
};

export const FILE_INFO_FIELD_LIST = {
  MOVIE: {
    fieldList: [
      CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DURATION,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DIRECTOR,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.MPAA,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CAST,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.GENRES,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.THEATRICAL,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.IFE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DISTRIBUTOR,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LAB,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.VERSION,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ORIGIN_COUNTRY_CODE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LOG_NO,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.AVAILABILITY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CATEGORY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.WIRELESS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DRM,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.IMDB,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.METACRITIC_CRITICS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ROTTEN_TOMATOES_AUDIENCE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ROTTEN_TOMATOES_CRITICS,
    ],
    fieldLabels: {
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.FORM_HEADING]: "File Information",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME]: "Original Title",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DURATION]: "Runtime",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS]: "Movie Rights",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS]:
        "Synopsis (max 300 characters)",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.METACRITIC_CRITICS]: "Metacritic",
    },
  },
  TV_SERIES: {
    fieldList: [
      CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.GENRES,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.MPAA,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CAST,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DISTRIBUTOR,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LAB,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ORIGIN_COUNTRY_CODE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CATEGORY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.IMDB,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.METACRITIC_CRITICS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ROTTEN_TOMATOES_AUDIENCE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ROTTEN_TOMATOES_CRITICS,
    ],
    fieldLabels: {
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.FORM_HEADING]: "Show Information",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME]: "Original Title",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE]: "Release Year",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS]: "Show Rights",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS]:
        "Synopsis (max 300 characters)",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.METACRITIC_CRITICS]: "Metacritic",
    },
  },
  PUBLICATION: {
    fieldList: [
      CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.WRITER,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.GENRES,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DISTRIBUTOR,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LAB,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.VERSION,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ORIGIN_COUNTRY_CODE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LOG_NO,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.AVAILABILITY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CATEGORY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.WIRELESS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DRM,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.METACRITIC_CRITICS,
    ],
    fieldLabels: {
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.FORM_HEADING]:
        "Publication Information",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME]: "Title",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE]: "Release Date",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS]: "Publication Rights",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.WRITER]: "Writer",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS]:
        "Description (max 300 characters)",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.METACRITIC_CRITICS]: "Critic Score",
    },
  },
  GAME: {
    fieldList: [
      CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CREATOR,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.MPAA,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.GENRES,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DISTRIBUTOR,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LAB,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.VERSION,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ORIGIN_COUNTRY_CODE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LOG_NO,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.AVAILABILITY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CATEGORY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.WIRELESS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DRM,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.METACRITIC_CRITICS,
    ],
    fieldLabels: {
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.FORM_HEADING]: "Game Information",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME]: "Title",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE]: "Release Date",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS]:
        "Synopsis (max 300 characters)",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.METACRITIC_CRITICS]: "Critic Score",
    },
  },
  EPISODE: {
    fieldList: [
      CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DURATION,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DIRECTOR,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.MPAA,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CAST,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.GENRES,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.THEATRICAL,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.IFE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.PRODUCTION_NO,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DISTRIBUTOR,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LAB,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.VERSION,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ORIGIN_COUNTRY_CODE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LOG_NO,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.AVAILABILITY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CATEGORY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.WIRELESS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DRM,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.IMDB,
    ],
    fieldLabels: {
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.FORM_HEADING]: "Episode Information",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME]: "Original Title",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DURATION]: "Duration",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE]: "Production Year",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS]: "Episode Rights",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS]:
        "Synopsis (max 300 characters)",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.PRODUCTION_NO]: "Production Code",
    },
  },
  SEASON: {
    fieldList: [
      CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.GENRES,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.MPAA,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CAST,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS,
    ],
    fieldLabels: {
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.FORM_HEADING]: "Season Information",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME]: "Original title",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE]: "Release Year",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS]: "Season Rights",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS]:
        "Synopsis (max 300 characters)",
    },
  },
  ARTIST: {
    fieldList: [
      CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.GENRES,
    ],
    fieldLabels: {
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.FORM_HEADING]: "Artist Information",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME]: "Artist Name",
    },
  },
  ALBUM: {
    fieldList: [
      CONFIG.FILE_INFO_FORM_FIELD_NAME.COVER,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.PRODUCTION_NO,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ISRC,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS,
    ],
    fieldLabels: {
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.FORM_HEADING]: "Album Information",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME]: "Album Title",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE]: "Release Date",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS]:
        "Album Synopsis (max 300 characters)",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.PRODUCTION_NO]: "Product ID",
    },
  },
  SONG: {
    fieldList: [
      CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DURATION,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.WRITER,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.FEATURED_ARTISTS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.GENRES,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.EXPLICIT,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.PRODUCTION_NO,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ISRC,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DISTRIBUTOR,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LAB,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ORIGIN_COUNTRY_CODE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LOG_NO,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.AVAILABILITY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CATEGORY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.WIRELESS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DRM,
    ],
    fieldLabels: {
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.FORM_HEADING]: "Song Information",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME]: "Song Title",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DURATION]: "Duration",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE]: "Release Year",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS]: "Song Rights",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.WRITER]: "Writer",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.PRODUCTION_NO]: "Product ID",
    },
  },
  PODCAST: {
    fieldList: [
      CONFIG.FILE_INFO_FORM_FIELD_NAME.COVER,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.GENRES,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.PRODUCERS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.HOSTS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS,
    ],
    fieldLabels: {
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.FORM_HEADING]: "Podcast Information",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME]: "Podcast Name",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS]:
        "Podcast Synopsis (max 300 characters)",
    },
  },
  AUDIOBOOK: {
    fieldList: [
      CONFIG.FILE_INFO_FORM_FIELD_NAME.COVER,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DURATION,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.NARRATOR,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.WRITER,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.GENRES,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.EXPLICIT,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.PRODUCTION_NO,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ISRC,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DISTRIBUTOR,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LAB,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.VERSION,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ORIGIN_COUNTRY_CODE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LOG_NO,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.AVAILABILITY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CATEGORY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.WIRELESS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DRM,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.METACRITIC_CRITICS,
    ],
    fieldLabels: {
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.FORM_HEADING]: "Audiobook Information",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME]: "Title",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DURATION]: "Duration",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS]: "Audiobook Rights",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE]: "Release",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.METACRITIC_CRITICS]: "Critic Score",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.WRITER]: "Author",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.PRODUCTION_NO]: "Product ID",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.SYNOPSIS]:
        "Synopsis (max 300 characters)",
    },
  },
  PODCAST_EPISODE: {
    fieldList: [
      CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DURATION,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CAST,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.GENRES,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.EXPLICIT,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.PRODUCTION_NO,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ISRC,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DISTRIBUTOR,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LAB,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.VERSION,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.ORIGIN_COUNTRY_CODE,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.LOG_NO,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.AVAILABILITY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.CATEGORY,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.WIRELESS,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.DRM,
      CONFIG.FILE_INFO_FORM_FIELD_NAME.METACRITIC_CRITICS,
    ],
    fieldLabels: {
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.FORM_HEADING]: "Episode Information",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.NAME]: "Episode Title",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DURATION]: "Duration",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.DATE]: "Release",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.RIGHTS]: "Episode Rights",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.PRODUCTION_NO]: "Production ID",
      [CONFIG.FILE_INFO_FORM_FIELD_NAME.METACRITIC_CRITICS]: "Critic Score",
    },
  },
};
export const OPEN_ENDPOINTS = [
  CONFIG.API_ENDPOINTS.LOGIN.href,
  CONFIG.API_ENDPOINTS.REFRESH_TOKEN.href,
  CONFIG.API_ENDPOINTS.REQUEST_RESET_PASSWORD.href,
  CONFIG.API_ENDPOINTS.RESET_PASSWORD.href,
];
